version: '3.7'

volumes:
    database: ~

services:
    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
            args:
                APP_USER_ID: 1000
                APP_GROUP_ID: 1000
        restart: on-failure
        volumes:
            - ./:/var/www/app:delegated

    nginx:
        image: nginx:1-alpine
        restart: on-failure
        depends_on:
            -   app
        ports:
            - "8010:80"
        volumes:
            - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/app/public

